name: aurora
version: "1.0.0"
profile: aurora

model-paths: ["models"]
macro-paths: ["macros"]

models:
  aurora:
    gold:
      +materialized: table
    ml:
      +materialized: table
      +schema: ml
